// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxlHA3dqbmm5q2CsGlWdH5JLv2qSECs4s',
    appId: '1:135037697911:web:58a33d0d9efce2f4672b72',
    messagingSenderId: '135037697911',
    projectId: 'mudanzaya-ddcd5',
    authDomain: 'mudanzaya-ddcd5.firebaseapp.com',
    storageBucket: 'mudanzaya-ddcd5.appspot.com',
    measurementId: 'G-KYHMQN1EGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKXGIWIFTKp4lPrVqQzI0u8ti9x-puaeo',
    appId: '1:135037697911:android:60b282949d901364672b72',
    messagingSenderId: '135037697911',
    projectId: 'mudanzaya-ddcd5',
    storageBucket: 'mudanzaya-ddcd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWLHyIgX6ueJfivTqx-_J0bIRGE4mfq5g',
    appId: '1:135037697911:ios:49e3e9bf6bf40cb2672b72',
    messagingSenderId: '135037697911',
    projectId: 'mudanzaya-ddcd5',
    storageBucket: 'mudanzaya-ddcd5.appspot.com',
    iosBundleId: 'com.lasthuman.mudanzaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWLHyIgX6ueJfivTqx-_J0bIRGE4mfq5g',
    appId: '1:135037697911:ios:caff957ec8ab8d66672b72',
    messagingSenderId: '135037697911',
    projectId: 'mudanzaya-ddcd5',
    storageBucket: 'mudanzaya-ddcd5.appspot.com',
    iosBundleId: 'com.lasthuman.mudanzaya.RunnerTests',
  );
}
